--CREATE DATABASE StockInventory

--USE StockInventory

CREATE TABLE Person
(
PersonID INT PRIMARY KEY IDENTITY(1,1),
LastName VARCHAR(50) NOT NULL,
FirstName VARCHAR(50) NOT NULL,
MiddleName VARCHAR(50),
Gender VARCHAR(10) NOT NULL,
Address VARCHAR(150),
ContactNumber VARCHAR(50),
Birthdate DATETIME,
Email VARCHAR(50)
)

CREATE TABLE Customer
(
CustomerID INT PRIMARY KEY IDENTITY(1,1),
PersonID INT NOT NULL FOREIGN KEY REFERENCES Person(PersonID),
)

CREATE TABLE CustomerBalance
(
CustomerBalance INT PRIMARY KEY IDENTITY(1,1),
CustomerID INT NOT NULL FOREIGN KEY REFERENCES Customer(CustomerID),
Balance DECIMAL(18,2) NOT NULL DEFAULT 0
)

CREATE TABLE [User]
(
UserID INT PRIMARY KEY IDENTITY(1,1),
Username VARCHAR(50) NOT NULL,
Password VARCHAR(MAX) NOT NULL,
SecretQuestion VARCHAR(150) NOT NULL,
SecretAnswer VARCHAR(150) NOT NULL,
IsActive BIT NOT NULL DEFAULT 1,
IsAdmin BIT NOT NULL DEFAULT 0
)

CREATE TABLE Employee
(
EmployeeID INT PRIMARY KEY IDENTITY(1,1),
PersonID INT NOT NULL FOREIGN KEY REFERENCES Person(PersonID),
UserID INT NOT NULL FOREIGN KEY REFERENCES [User](UserID),
IsActive BIT NOT NULL DEFAULT 1
)

CREATE TABLE Brand
(
BrandID INT PRIMARY KEY IDENTITY(1,1),
Name VARCHAR(50) NOT NULL
)

CREATE TABLE Product
(
ProductID INT PRIMARY KEY IDENTITY(1,1),
BrandID INT FOREIGN KEY REFERENCES Brand(BrandID),
Name VARCHAR(100) NOT NULL,
Description VARCHAR(250),
Price DECIMAL(18,2),
IsActive BIT NOT NULL DEFAULT 1
)

CREATE TABLE ProductImage
(
ProductImageID INT PRIMARY KEY IDENTITY(1,1),
ProductID INT NOT NULL FOREIGN KEY REFERENCES Product(ProductID),
Url VARCHAR(500),
Base64String VARCHAR(MAX)
)

CREATE TABLE Supplier
(
SupplierID INT PRIMARY KEY IDENTITY(1,1),
Name VARCHAR(100) NOT NULL
)

CREATE TABLE OrderStatus
(
OrderStatusID INT PRIMARY KEY IDENTITY(1,1),
Name VARCHAR(50) NOT NULL
)
--INSERT INTO OrderStatus VALUES('ONGOING')
--INSERT INTO OrderStatus VALUES('COMPLETED')
--INSERT INTO OrderStatus VALUES('CANCELLED')

CREATE TABLE [Order]
(
OrderID INT PRIMARY KEY IDENTITY(1,1),
OrderStatusID INT NOT NULL FOREIGN KEY REFERENCES OrderStatus(OrderStatusID),
EmployeeID INT NOT NULL FOREIGN KEY REFERENCES Employee(EmployeeID),
SupplierID INT FOREIGN KEY REFERENCES Supplier(SupplierID),
TotalAmount DECIMAL(18,2),
DateOrdered DATETIME NOT NULL,
DateDelivered DATETIME,
DateModified DATETIME,
ModifierID INT FOREIGN KEY REFERENCES Employee(EmployeeID)
)

CREATE TABLE OrderDetail
(
OrderDetailID INT PRIMARY KEY IDENTITY(1,1),
OrderID INT NOT NULL FOREIGN KEY REFERENCES [Order](OrderID),
ProductID INT NOT NULL FOREIGN KEY REFERENCES Product(ProductID),
Price DECIMAL(18,2) NOT NULL,
Quantity INT NOT NULL,
Amount DECIMAL(18,2) NOT NULL
)

CREATE TABLE Sale
(
SaleID INT PRIMARY KEY IDENTITY(1,1),
EmployeeID INT NOT NULL FOREIGN KEY REFERENCES Employee(EmployeeID),
CustomerID INT FOREIGN KEY REFERENCES Customer(CustomerID),
TotalAmount DECIMAL(18,2),
DateSold DATETIME NOT NULL,
IsVoid BIT NOT NULL DEFAULT 0,
DateModified DATETIME,
ModifierID INT FOREIGN KEY REFERENCES Employee(EmployeeID)
)

CREATE TABLE SaleDetail
(
SaleDetailID INT PRIMARY KEY IDENTITY(1,1),
SaleID INT NOT NULL FOREIGN KEY REFERENCES Sale(SaleID),
ProductID INT NOT NULL FOREIGN KEY REFERENCES Product(ProductID),
Price DECIMAL(18,2) NOT NULL,
Quantity INT NOT NULL,
Amount DECIMAL(18,2) NOT NULL
)